package com.tool.soat.dao;

import com.tool.soat.entity.SoatSet;

public interface SoatSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    int insert(SoatSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    int insertSelective(SoatSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    SoatSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoatSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoatSet record);
}