package com.tool.soat.dao;

import com.tool.soat.entity.SoatUsersRoles;

public interface SoatUsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users_roles
     *
     * @mbggenerated
     */
    int insert(SoatUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users_roles
     *
     * @mbggenerated
     */
    int insertSelective(SoatUsersRoles record);
}