package com.tool.soat.dao;

import com.tool.soat.entity.SoatInterface;

public interface SoatInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    int insert(SoatInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    int insertSelective(SoatInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    SoatInterface selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoatInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_interface
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoatInterface record);
}