package com.tool.soat.dao;

import com.tool.soat.entity.SoatDevices;

public interface SoatDevicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    int insert(SoatDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    int insertSelective(SoatDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    SoatDevices selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoatDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_devices
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoatDevices record);
}