package com.tool.soat.dao;

import com.tool.soat.entity.SoatUsers;

import java.util.List;

public interface SoatUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    int insert(SoatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    int insertSelective(SoatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    SoatUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SoatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SoatUsers record);


    SoatUsers queryUserByUsername(String username);

    List<SoatUsers> queryAllUserBySizeAndNum(Integer pagesize, Integer pagenum,String username);

    SoatUsers queryEmailOrPhoneD(String email, String phone);
    SoatUsers queryEmailOrPhoneOrNameD(String username, String email, String phone);
    SoatUsers queryUserD(Integer id);
}