package com.tool.soat.dao;

import com.tool.soat.entity.SoatIdNumber;

public interface SoatIdNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    int insert(SoatIdNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    int insertSelective(SoatIdNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    SoatIdNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoatIdNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_id_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoatIdNumber record);
}