package com.tool.soat.dao;

import com.tool.soat.entity.SoatRoles;

import java.util.Set;

public interface SoatRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_roles
     *
     * @mbggenerated
     */
    int insert(SoatRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_roles
     *
     * @mbggenerated
     */
    int insertSelective(SoatRoles record);

    Set<String> queryRoleNameByUsernames(String username);




}