package com.tool.soat.dao;

import com.tool.soat.entity.SoatNav;

import java.util.List;

public interface SoatNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    int insert(SoatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    int insertSelective(SoatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    SoatNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoatNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoatNav record);

    List<SoatNav> selectAllNav();

    List<SoatNav> selectByLevel(Integer id);
}