package com.tool.soat.dao;

import com.tool.soat.entity.SoatPermission;

import java.util.Set;

public interface SoatPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_permission
     *
     * @mbggenerated
     *
     */

    Set<String> queryPermissionByUsername(String username);

    int insert(SoatPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_permission
     *
     * @mbggenerated
     */
    int insertSelective(SoatPermission record);



}