package com.tool.soat.dao;

import com.tool.soat.entity.SoatRolesPermissions;

public interface SoatRolesPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_roles_permissions
     *
     * @mbggenerated
     */
    int insert(SoatRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_roles_permissions
     *
     * @mbggenerated
     */
    int insertSelective(SoatRolesPermissions record);
}