package com.tool.soat.entity;

import lombok.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

@Data
@ToString
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class SoatNav implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_nav.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_nav.nav_name
     *
     * @mbggenerated
     */
    private String navName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_nav.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_nav.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table soat_nav
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private List<SoatNav> list = new LinkedList<>();

}