package com.tool.soat.entity;

import java.io.Serializable;

public class SoatRolesPermissions implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_roles_permissions.r_id
     *
     * @mbggenerated
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column soat_roles_permissions.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table soat_roles_permissions
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column soat_roles_permissions.r_id
     *
     * @return the value of soat_roles_permissions.r_id
     *
     * @mbggenerated
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column soat_roles_permissions.r_id
     *
     * @param rId the value for soat_roles_permissions.r_id
     *
     * @mbggenerated
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column soat_roles_permissions.p_id
     *
     * @return the value of soat_roles_permissions.p_id
     *
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column soat_roles_permissions.p_id
     *
     * @param pId the value for soat_roles_permissions.p_id
     *
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soat_roles_permissions
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rId=").append(rId);
        sb.append(", pId=").append(pId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}